### ISSUE TITLE
Not searching dleyna://xxx: Keyword "any" not supported by device

### ISSUE THREAD

**Issue by anthonydahanne** [tkem/mopidy-dleyna#52]
Hello,
I've just installed mopidy-dleyna, and when trying to do some searches using Mopidy-MusicBox-Webclient, I have such output in the logs : 

```
2016-07-15 16:11:35,608 WARNING [3047:dLeynaBackend-7] mopidy_dleyna.library: Not searching dleyna://uuidXXX: Keyword "any" not supported by device
```

Did I miss something ?
My DLNA server is a Synology DSM

Thanks

**Comment by tkem** [comment]
Well, the warning just indicates that searching for keyword `any` (which your client sends to the Mopidy server when you don't specifically search for artist, album, etc.) are not supported by your DLNA server. Which probably means that searching isn't supported at all.

**Comment by anthonydahanne** [comment]
hey there,
thanks for your quick answer...
Well it appears you are right : https://forum.synology.com/enu/viewtopic.php?t=46162 or even https://forum.synology.com/enu/viewtopic.php?t=73340

I'll close the ticket since it's obviously not a modipy-dleyna issue

thanks again, useful extension !

**Comment by tkem** [comment]
Reopening this as a reminder to change log message if search is not supported at all. Use of the `any` keyword might be confusing/misleading for end users. Note there's already a `TODO` in `translator.py` for this.
