### ISSUE TITLE
Please check for XDG_RUNTIME_DIR/bus before running dbus-launch

### ISSUE THREAD

**Issue by jodal** [tkem/mopidy-dleyna#55]
Quoting https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=836117:

> As described in https://lists.debian.org/debian-devel/2016/08/msg00554.html
> I'm trying to reduce how much dbus-launch is used in Debian.
> mopidy-dleyna currently runs dbus-launch in __start_dbus()
> if DBUS_SESSION_BUS_ADDRESS is unset.
> 
> One issue with this approach is that it second-guesses how the D-Bus
> client implementation itself will find the session bus. In recent libdbus
> and GDBus, the fallback behaviour if DBUS_SESSION_BUS_ADDRESS is unset
> is to look for $XDG_RUNTIME_DIR/bus: if the environment variable is
> set, that directory contains ./bus, and ./bus is a socket owned by
> the current uid, then libdbus and GDBus will automatically use it. In
> particular, the dbus-user-session Debian package sets up this situation.
> mopidy-dleyna should not run dbus-launch without first looking
> for that socket.
> 
> Another issue with the approach this package has taken is that it relies
> on dbus-launch, which is X11-specific legacy code that does several
> things, none of them particularly well.
> This Flatpak commit illustrates how eval `dbus-launch` can be replaced
> by invoking dbus-daemon directly, avoiding the X11-specific dbus-launch:
> https://github.com/flatpak/flatpak/commit/6cc8062cfb3f9410d54a27e7ccca77c103e441e8.
> It is possible to send both the address and the pid to stdout
> ("--print-address=1 --print-pid=1") if that would be easier to deal
> with; their order is undocumented but predictable, and I don't intend
> to break it in future D-Bus releases.
> 
> Alternatively, and perhaps most simply, this package could stop trying to
> compensate for a missing session bus address at all. On systems with
> $XDG_RUNTIME_DIR/bus, it would "just work" anyway; or when run under X11
> (even with no dbus-daemon running), X11 autolaunching would create a
> dbus-daemon anyway; or if it is being run in a non-GUI environment like
> cron, its documentation could mention that this may require using
> 
> ```
> dbus-run-session -- COMMAND [ARGS...]
> ```
> 
> which has been available since dbus 1.8, and automatically cleans up
> the dbus-daemon after COMMAND terminates (successfully or not).
> 
> This is really an upstream bug. If you forward it upstream, please
> quote the full text of this bug report and let upstream make their
> own decisions.
> 
> Thanks,
>     S

**Comment by tkem** [comment]
Thanks, will look into this later this week. Just FYI, I added the `dbus-launch` stuff explicitly for running Mopidy as a service (without knowing exactly what I was doing, frankly); also the X11 autolaunching is generally not an option.

**Comment by tkem** [comment]
So would this check replace checking for DBUS_SESSION_BUS_ADDRESS in the environment?

**Comment by tkem** [comment]
I think using `dbus-run-session` is not an option, since this would require changing Mopidy's startup scripts when running as a service.

**Comment by tkem** [comment]
Seems to be pretty hard to test, since even when running a mopidy instance as a local user, there is no `$XDG_RUNTIME_DIR/bus` on my Debian jessie system.

**Comment by tkem** [comment]
Also turns out there's no `dbus-user-session` in jessie.

**Comment by tkem** [comment]
@jodal: Done (at least I think so).
Please note that Mopidy-dLeyna v1.2.0 no longer requires `dbus-launch` by default, so this dependency (`dbus-x11`) can be removed from the Debian package, eventually.

**Comment by jodal** [comment]
Without having studied the details here, your change looks good to me. Thanks :-)

**Comment by tkem** [comment]
Thank _you_ ;-)

**Comment by jodal** [comment]
Well, now I have to do something too: 1.2.0 debs uploaded to apt.mopidy.com and Debian :-)
