### ISSUE TITLE
dlna server not found

### ISSUE THREAD

**Issue by mczerski** [tkem/mopidy-dleyna#57]
hi,

i have a dlna server on my linksys router and couple of linux boards running mopidy. they are configured almost the same, but one of them can't find the dlna server. i don't really know where to start to solve this problem. the mopidy service logs don't really tell me what might be wrong.

**Comment by mczerski** [comment]
i'm stupid, after reboot the server is found ...

**Comment by tkem** [comment]
Glad it works now. Device discovery is tricky, sometimes...
