### ISSUE TITLE
can't play next song

### ISSUE THREAD

**Issue by mczerski** [tkem/mopidy-dleyna#58]
when playing songs from dlna server, after song is finished the next one is not played. i have to hit stop and then play to play next song in the current track list.

**Comment by tkem** [comment]
Doesn't sound like a dleyna issue to me - have you tried other backends (file, local, spotify, ...)?

**Comment by mczerski** [comment]
i'm using spotify and there is no problems. but checked also with youtube and there is the same problem as with dleyna ... so yeah, probably it is more general problem :/ no errors in the log.
if i mix songs from spotify with dlna songs, then next song works only if next is from spotify.

**Comment by mczerski** [comment]
i'm using mopidy 2.0.1 and mopidy-dleyna 1.2.0, all installed with pip. so no one else has this problem ?

**Comment by tkem** [comment]
If this happens with other backends as well, you might get better answers posting this to https://discuss.mopidy.com

**Comment by mczerski** [comment]
well, i don't really know if it happens with youtube also, i have similar problem with one youtube song but this song has also problems with rewinding, all other youtube songs i tested didn't have any problems.

**Comment by mczerski** [comment]
ok, sorry for trouble. it was my changes to the mopidy that caused this behaviour ...

**Comment by tkem** [comment]
No problem!
