### ISSUE TITLE
Lost digital media server

### ISSUE THREAD

**Issue by magcode** [tkem/mopidy-dleyna#60]
I'm looking for help how to tackle this issue.

Running Mopidy on a RPI zero directly using

`mopidy -vvv --config /etc/mopidy/mopidy.conf`

It connects to the media server 
```
INFO     2017-08-14 13:26:49,789 [5446:MainThread] mopidy_dleyna.client
  Found digital media server Serviio (quentin) [uuid:84052123-d4a8-3050-acdd-7d9fca8e4d8a]
```

30mins later I get
```
INFO     2017-08-14 13:56:49,462 [5446:MainThread] mopidy_dleyna.client
  Lost digital media server Serviio (quentin) [uuid:84052123-d4a8-3050-acdd-7d9fca8e4d8a]
```
  
Installed packages:

```
dleyna-server/oldstable,now 0.4.0-1 armhf [installed,automatic]
libdleyna-connector-dbus-1.0-1/oldstable,now 0.2.0-1 armhf [installed,automatic]
libdleyna-core-1.0-3/oldstable,now 0.4.0-1 armhf [installed,automatic]
mopidy-dleyna/stable,now 1.2.0-1 all [installed]
mopidy/stable,now 2.1.0-1 all [installed]
```

I also runned 

```
export GUPNP_DEBUG=1
dbus-daemon --fork --session --print-pid=1
```

but /var/log/messages does only output this:

https://gist.githubusercontent.com/magcode/547c1e49d776cd06ab4258320f9e6e84/raw/5dc6d6392597330fb5372e503e7b5fb89ed06901/message.log

Thanks

**Comment by tkem** [comment]
I don't know "Serviio", but I've seen similar behavior with Kodi DLNA server, and occasionally also with minidlna, especially on a Mopidy installation that's connected via a WiFi repeater. However, servers are usually "found again" after a couple of seconds, except in case of network problems. I've rarely, if ever, seen this on my other Mopidy installation which uses a wired connection.

So this may be either server or network related, but for me this was never much of an issue - I also can't remember ever seeing this happen to a media server that was actively used at the time.

**Comment by magcode** [comment]
Thanks
its a wired network and I meanwhile tried a different DNLA server on the same host as "Serviio" ... same result: timeout after 30mins

I'll investigte further, will install a server on a completely different box.

I was also thinking about networking issues, but my SSH sessions to the Mopidy box stays open and those exactly 30min timeouts do not sound like random networking issues.

**Comment by magcode** [comment]
I think it has nothing to do with the DLNA server. Tested 3 different servers on two different hosts.

```
INFO     2017-08-15 08:11:47,634 [6077:MainThread] mopidy_dleyna.client
  Found digital media server OBELIX [uuid:4d696e69-444c-164e-9d41-00089bbdc165]
INFO     2017-08-15 08:11:47,671 [6077:MainThread] mopidy_dleyna.client
  Found digital media server Serviio (quentin) [uuid:84052123-d4a8-3050-acdd-7d9                                fca8e4d8a]
INFO     2017-08-15 08:11:48,905 [6077:MainThread] mopidy_dleyna.client
  Found digital media server TV Server (QUENTIN) [uuid:A13ED507-C036-49A9-956A-7                                9A213DDF448]
INFO     2017-08-15 08:41:46,742 [6077:MainThread] mopidy_dleyna.client
  Lost digital media server TV Server (QUENTIN) [uuid:A13ED507-C036-49A9-956A-79A213DDF448]
INFO     2017-08-15 08:41:48,738 [6077:MainThread] mopidy_dleyna.client
  Lost digital media server Serviio (quentin) [uuid:84052123-d4a8-3050-acdd-7d9fca8e4d8a]
INFO     2017-08-15 08:41:56,743 [6077:MainThread] mopidy_dleyna.client
  Lost digital media server OBELIX [uuid:4d696e69-444c-164e-9d41-00089bbdc165]
```

**Comment by tkem** [comment]
As you said, it doesn't seem an issue with Serviio, but maybe this will still be helpful:

http://forum.serviio.org/viewtopic.php?f=5&t=10289

Any chance you use a D-Link router?

**Comment by tkem** [comment]
Since I assume you're running mopidy on a Raspberry Pi, you could also install minidlna locally for testing purposes. After `apt-get install minidlna`, you'll just have to edit `/etc/minidlna.conf` to make sure it binds to the loopback device:
```
# Network interface(s) to bind to (e.g. eth0), comma delimited.
# This option can be specified more than once.
network_interface=lo
```
If this issue does *not* occur with the local DLNA server, I think it's safe to say that it *is* probably related to your network infrastructure in some way.

**Comment by magcode** [comment]
Indeed no connection drop with minidlna on localhost/loopback.
I doubt it has something to do with the switch (Netgear Prosafe Plus). No connection drop issues on other consuming devices such as TV.

I close this as it is not a Mopidy issue. Thanks a lot @tkem for your help investigating the issue!

**Comment by tkem** [comment]
I wouldn't rule out router settings/issues completely - other clients, such as smart TVs, may choose to e.g. simply ignore "server lost" events, and so you wouldn't necessarily notice. And though I see these on my Pi once in a while, I've never experienced this while actively streaming from the server. So this may go unnoticed (unless you have access to your TV's log file, which I don't ;-)

**Comment by tkem** [comment]
Anyway, if you manage to find a solution for your issue, please let me know. I may add something about it on the README page, for future reference.

**Comment by magcode** [comment]
Finally found it. It was caused by a (too) cheap USB LAN adapter. 🤦‍♂️  Now using an "UGREEN 20253" which is working fine.

**Comment by tkem** [comment]
Interesting... Would have never thought of that! Great that it works for you now, though!
