### ISSUE TITLE
some items not visible

### ISSUE THREAD

**Issue by wdehoog** [tkem/mopidy-dleyna#62]
I am using minimserver as content server and some items are not shows by mopidy-dleyna that are visible with other upnp applications. 

It looks like items with upnp:class object.item.audioItem.musicTrack are shown but not when it is object.item.audioItem.audioBroadcast.

So all my music tracks are visible but not the internet radio streams (which I have put in m3u files but which minimserver expands).

**Comment by tkem** [comment]
Interesting, I expected all `audioItem` types to be treated as Mopidy "tracks".

You can find the list of recognized dLeyna `TypeEx` properties [here](https://github.com/tkem/mopidy-dleyna/blob/master/mopidy_dleyna/translator.py#L39). You may want to try adding something like
```
'item.audioItem.audioBroadcast': models.Ref.track,
```
i.e. the `upnp:class` with the leading `object.` removed. However, according to the dLeyna [documentation](https://github.com/intel/dleyna-server/blob/master/doc/server/dbus/API.txt#L538) I was expecting this to be mapped to just `audio`, just as `object.item.audioItem.musicTrack` is mapped to `music`.

**Comment by wdehoog** [comment]
Thanks. I had to add these to get it working

    'container.playlistContainer': models.Ref.directory,
    'item.audioItem.audioBroadcast': models.Ref.track,

**Comment by tkem** [comment]
Great, thanks for trying this out! I'll add these (and `item.audioItem.audioBook`, probably too, then) in the next release.
