### ISSUE TITLE
Track info not showing on mopidy-iris

### ISSUE THREAD

**Issue by tatealive** [tkem/mopidy-dleyna#71]
Please see full discussion here https://github.com/jaedb/Iris/issues/661#issuecomment-754476796
 - track info sent from mopidy-dleyna is not showing in mopidy-iris

**Comment by kingosticks** [comment]
Not a Mopidy-dleyna issue in my opinion. Nothing should infer information from a Mopidy URI except the backend that created it.

**Comment by tkem** [comment]
@kingosticks is right, of course ;-)

Note that similar issues probably exist with mopidy-podcast, mopidy-internetarchive, and probably many other extensions that do not follow the `provider:type:id` URI scheme that Iris requires.
