### ISSUE TITLE
Lookup returns objects with lowercase-encoded URIs

### ISSUE THREAD

**Issue by jaedb** [tkem/mopidy-dleyna#72]
Running `library.lookup` on a dLeyna URI returns a matched result, however the result's URI does not always match that of the query on account for case insensitivity of URI encoding.

---
### To replicate
1. Get a valid dLeyna track URI for your environment, eg `dleyna://uuid:0011322a-eb03-0011-03eb-03eb2a321100/3234243133383336312440313338333739`
2. Perform a Mopidy lookup request on that URI, eg:
```
curl -d '{"jsonrpc": "2.0", "id": 1, "method": "core.library.lookup", "params": {"uris": ["dleyna://uuid:0011322a-eb03-0011-03eb-03eb2a321100/3234243133383336312440313338333739"]}}' -H 'Content-Type: application/json' http://localhost:6680/mopidy/rpc
```
3. Observe the response, which includes `uri` with the value of `dleyna://uuid%3a0011322a-eb03-0011-03eb-03eb2a321100/3234243133383336312440313338333739`, ie NOT what we had requested.
```
{"jsonrpc": "2.0", "id": 1, "result": {"dleyna://uuid:0011322a-eb03-0011-03eb-03eb2a321100/3234243133383336312440313338333739": [{"__model__": "Track", "uri": "dleyna://uuid%3a0011322a-eb03-0011-03eb-03eb2a321100/3234243133383336312440313338333739", "name": "Annihilation", "artists": [{"__model__": "Artist", "name": "A Perfect Circle"}], "album": {"__model__": "Album", "name": "eMOTIVe"}, "genre": "Rock", "track_no": 1, "date": "2004-01-01", "length": 134000, "bitrate": 192000}]}}
```
---
The big issue here is the use of lowercase URI encoding. `%3a` should in fact be `%3A`.

### To fix
Encode URIs to uppercase characters (UTF-8?).

**Comment by tkem** [comment]
@jaedb: Sorry for the late response, this kept me puzzled for a while.
It turned out this is probably a bug in a dependency, see https://github.com/tkem/uritools/issues/66.
So this should be fixed with the next version of `uritools`.
Sorry for the inconvenience!

**Comment by jaedb** [comment]
Hehe no sweat, I understand. Sounds good, cheers for the update 👍

**Comment by tkem** [comment]
Upgrading `uritools` to v3.0.1 should fix this: https://github.com/tkem/uritools/blob/master/CHANGELOG.rst
